[[positions]]
id = "NAT_FSS"
prefixes = ["NAT"]
frequency = "131.900"
facility_type = "FSS"
default_call_sources = ["NAT_BBx"]
# Default call source backup - they should use a Shanwick/Gander source as required for that coordination

[[positions]]
id = "EGGX_CTR"
prefixes = ["EGGX"]
frequency = "131.800"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick"]

[[positions]]
id = "EGGX_A_CTR"
prefixes = ["EGGX"]
frequency = "131.450"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_A"]

[[positions]]
id = "EGGX_1_CTR"
prefixes = ["EGGX"]
frequency = "131.450"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_A"]

[[positions]]
id = "EGGX_B_CTR"
prefixes = ["EGGX"]
frequency = "131.550"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_B"]

[[positions]]
id = "EGGX_2_CTR"
prefixes = ["EGGX"]
frequency = "131.550"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_B"]

[[positions]]
id = "EGGX_C_CTR"
prefixes = ["EGGX"]
frequency = "131.650"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_C"]

[[positions]]
id = "EGGX_3_CTR"
prefixes = ["EGGX"]
frequency = "131.650"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_C"]

[[positions]]
id = "EGGX_D_CTR"
prefixes = ["EGGX"]
frequency = "131.750"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_D"]

[[positions]]
id = "EGGX_4_CTR"
prefixes = ["EGGX"]
frequency = "131.750"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_D"]

[[positions]]
id = "EGGX_F_CTR"
prefixes = ["EGGX"]
frequency = "131.850"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_F"]

[[positions]]
id = "EGGX_5_CTR"
prefixes = ["EGGX"]
frequency = "131.850"
facility_type = "CTR"
profile_id = "EGGX"
default_call_sources = ["Shanwick_F"]

[[positions]]
id = "EGGX_DEL"
prefixes = ["EGGX"]
frequency = "127.650"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL"]

[[positions]]
id = "EGGX_A_DEL"
prefixes = ["EGGX"]
frequency = "127.900"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_A"]

[[positions]]
id = "EGGX_1_DEL"
prefixes = ["EGGX"]
frequency = "127.900"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_A"]

[[positions]]
id = "EGGX_B_DEL"
prefixes = ["EGGX"]
frequency = "123.950"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_B"]

[[positions]]
id = "EGGX_2_DEL"
prefixes = ["EGGX"]
frequency = "123.950"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_B"]

[[positions]]
id = "EGGX_C_DEL"
prefixes = ["EGGX"]
frequency = "124.175"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_C"]

[[positions]]
id = "EGGX_3_DEL"
prefixes = ["EGGX"]
frequency = "124.175"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_C"]

[[positions]]
id = "EGGX_D_DEL"
prefixes = ["EGGX"]
frequency = "126.375"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_D"]

[[positions]]
id = "EGGX_4_DEL"
prefixes = ["EGGX"]
frequency = "126.375"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_D"]

[[positions]]
id = "EGGX_F_DEL"
prefixes = ["EGGX"]
frequency = "128.375"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_F"]

[[positions]]
id = "EGGX_5_DEL"
prefixes = ["EGGX"]
frequency = "128.375"
facility_type = "DEL"
profile_id = "EGGX"
default_call_sources = ["Shanwick_DEL_F"]
